import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { createClient } from "next-sanity";
import Author from './author';
import Category from './Category';
import Post from './Post';
// import BlockContent from "@sanity/block-content-to-react";

export default function Home({ author, category, post }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Post post={post} />
      <Category category={category} />
      <Author author={author} />
    </div>
  )
}


const client = createClient({
  projectId: "eptiw9x7",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false
});

export async function getStaticProps() {
  const category = await client.fetch(`*[_type == "category"]{_id,title,description}`);

  const author = await client.fetch(`*[_type == "author"]{
    _id, name,
    'slug': slug.current,
    bio,blockContent,
    'picture': image,
    'image':image.asset->url,
  }`);

  const post = await client.fetch(`*[_type == "post"]{
    _id,
    title,
    'slug': slug.current,
    'image': mainImage,
    'date' : publishedAt,
    body,
    'categories': categories[]->{title,description},
    'author': author->{name,  blockContent,bio,'slug': slug.current, 'picture': image.asset->url},
  }`);

  return {
    props: {
      category, author, post
    }
  };
}
